 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var dateformat = require('dateformat');
var fs = require('fs');
var express = require('express');
var app = express();

if (!process.env.DISABLE_XORIGIN) {
  app.use(function(req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

app.use('/public', express.static(process.cwd() + '/public'));

/* I'm adding this code! */
// TODO Update this later to just generically check, not using /api/:
app.use('/api/', (req,res,next) => {
        res.type('txt').send('API!');
    next();
    })

app.route('/_api/package.json')
  .get(function(req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function(err, data) {
      if(err) return next(err);
      res.type('txt').send(data.toString());
    });
  });
  
app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })


function isValidDateString(dateStr) { 
  const d = new Date(dateStr).getTime()
  console.log("input date string = "+dateStr+"....d = "+d)
  return (new Date(dateStr).getTime() > 0)
}

function isValidDate(date) {
  if (date == null) return false
  
  return date.getTime() > 0
}

function returnJSONDateInfo(date, res) {
  var dateObj = {"unix":"","natural":""}
  
  if ()
  
  dateObj["unix"] = (date.getTime() / 1000).toFixed(0)  
  dateObj["natural"] = dateformat(date,"mmmm d, yyyy")
  
  res.type('txt').send(JSON.stringify(dateObj))
}

app.use(function(req, res, next){
  const dateString = req.url.toString().slice(1) // remove the '/' from the url
  
  // if (!isValidDateString(dateString)) {
  //   res.type('txt').send(JSON.stringify({"unix":null,"natural":null}))
  // } else {
    // Check if it is a unix timestamp or a natural language date:  
    if (isNaN(parseInt(dateString))) {
      // Natural Language Date

      const nlDate = new Date(decodeURI(dateString))
      returnJSONDateInfo(nlDate, res)

    } else {
      // Unix Timestamp

      const date = new Date(parseInt(dateString)*1000) // convert unix timestamp to date
      returnJSONDateInfo(date, res)    
    }
  //}

  
  
  // Respond not found to all the wrong routes
  //res.status(404);
  //res.type('txt').send('Not found');
  next();
});

// Error Middleware
app.use(function(err, req, res, next) {
  if(err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }  
})

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

